add ilo5 2.30 to firmware list
seveas/python-hpilo pull request #239
Opened 2020-10-12 13:52 UTC by sean0

2020-10-18 13:44 UTC, seveas requested changes
Could you update the `[ilo5]` section as well please?

2020-10-19 14:38 UTC, sean0 commented
> Could you update the `[ilo5]` section as well please?

Of course, sorry I missed that!

2020-10-19 15:47 UTC, seveas approved these changes

2020-10-19 15:47 UTC, merged

2020-10-19 15:47 UTC, seveas commented
Thanks!